version: '3.8'

services:
  astro-cms:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true

  # Optional: Add a database if you want to store metadata
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: astro_cms
  #     POSTGRES_USER: cms_user
  #     POSTGRES_PASSWORD: cms_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: